/**
 * Client-side ZIP builder for exports.
 *
 * Two modes:
 * - "lightroom": photos (original) + XMP sidecars + README
 * - "full": photos at original resolution (no XMP)
 * - "mls": photos resized to MLS spec (max 2MB, 2048px long edge)
 */

import JSZip from "jszip";

interface Sidecar {
  photoFileName: string;
  xmpFileName: string;
  xmpContent: string;
  photoUrl: string;
  qcScore: number | null;
  status: string;
}

interface ZipProgress {
  phase: "fetching-xmp" | "downloading" | "zipping" | "done";
  done: number;
  total: number;
  currentFileName?: string;
}

const README_TEXT = `AutoQC Lightroom Export
=======================

This folder contains your property photos paired with XMP sidecar files
that carry all of AutoQC's recommended adjustments.

HOW TO USE
----------

For RAW files (CR2, NEF, ARW, DNG, etc.):
  1. Drag the whole folder into Lightroom
  2. Adjustments apply automatically

For JPEG files (most users):
  1. Drag the whole folder into Lightroom
  2. Select all photos (Cmd/Ctrl + A)
  3. Go to Metadata menu > Read Metadata from Files
  4. AutoQC's adjustments are now applied

You can also use Adobe Camera Raw (via Bridge or Photoshop) which reads
XMP sidecars automatically with no extra step.

WHAT GETS APPLIED
-----------------

Every photo has a matching .xmp file that contains the AutoQC-recommended
Lightroom adjustments: exposure, highlights, shadows, white balance,
saturation, clarity, upright/straighten, lens correction, etc.

Adjustments are non-destructive. You can tweak any slider after import.

NOTE
----

XMP sidecars work alongside the original photo. Do NOT rename either file
or separate them - they must stay paired and in the same folder for
Lightroom to link them.

Generated by AutoQC - autoqc.io
`;

export async function downloadLightroomZip(
  propertyId: string,
  propertyAddress: string,
  onProgress?: (p: ZipProgress) => void
): Promise<void> {
  const update = (p: ZipProgress) => onProgress?.(p);

  // 1. Get sidecar manifest from server
  update({ phase: "fetching-xmp", done: 0, total: 1 });
  const res = await fetch(`/api/properties/${propertyId}/xmp`);
  if (!res.ok) {
    throw new Error("Failed to fetch XMP manifest");
  }
  const data = await res.json();
  const sidecars: Sidecar[] = data.sidecars || [];

  if (sidecars.length === 0) {
    throw new Error("No photos to export");
  }

  // 2. Build the zip by streaming each photo in
  const zip = new JSZip();
  zip.file("README.txt", README_TEXT);

  update({
    phase: "downloading",
    done: 0,
    total: sidecars.length,
  });

  // Parallelize photo downloads (4 at a time)
  const queue = [...sidecars];
  let completed = 0;

  const worker = async () => {
    while (queue.length > 0) {
      const sc = queue.shift();
      if (!sc) break;

      update({
        phase: "downloading",
        done: completed,
        total: sidecars.length,
        currentFileName: sc.photoFileName,
      });

      try {
        const photoRes = await fetch(sc.photoUrl);
        if (photoRes.ok) {
          const blob = await photoRes.blob();
          zip.file(sc.photoFileName, blob);
        }
        zip.file(sc.xmpFileName, sc.xmpContent);
      } catch (err) {
        console.error("Failed to fetch", sc.photoFileName, err);
      }
      completed++;
      update({
        phase: "downloading",
        done: completed,
        total: sidecars.length,
      });
    }
  };

  await Promise.all([worker(), worker(), worker(), worker()]);

  // 3. Generate the zip
  update({ phase: "zipping", done: 0, total: 1 });
  const zipBlob = await zip.generateAsync(
    { type: "blob", compression: "STORE" }, // STORE = no compression (jpegs don't compress anyway)
    (metadata) => {
      update({
        phase: "zipping",
        done: Math.round(metadata.percent),
        total: 100,
      });
    }
  );

  // 4. Trigger download
  const safeAddress = propertyAddress
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 60);
  const zipName = `AutoQC_${safeAddress || "export"}.zip`;

  const url = URL.createObjectURL(zipBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = zipName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  update({ phase: "done", done: sidecars.length, total: sidecars.length });
}
