/**
 * Client-side photo export ZIP builder.
 *
 * Three modes:
 * - "lightroom": photos at original resolution + XMP sidecars + README
 * - "full": photos at original resolution (no XMP)
 * - "mls": photos resized to MLS spec (max 2MB, 2048px long edge)
 */

import JSZip from "jszip";

interface Sidecar {
  photoFileName: string;
  xmpFileName: string;
  xmpContent: string;
  photoUrl: string;
  qcScore: number | null;
  status: string;
}

interface ZipProgress {
  phase: "fetching-xmp" | "downloading" | "resizing" | "zipping" | "done";
  done: number;
  total: number;
  currentFileName?: string;
}

const README_LIGHTROOM = `AutoQC Lightroom Export
=======================

Photos + XMP sidecars with AutoQC's recommended Lightroom adjustments.

HOW TO USE
----------
For RAW files: Drag the folder into Lightroom - adjustments apply automatically.

For JPEG files:
  1. Drag the folder into Lightroom
  2. Select all photos (Cmd/Ctrl + A)
  3. Metadata menu > Read Metadata from Files
  4. AutoQC adjustments now applied

Tweak any slider afterward - all adjustments are non-destructive.

Generated by AutoQC - autoqc.io
`;

const README_MLS = `AutoQC MLS Export
==================

All photos resized to meet MLS specifications:
  - Max 2MB file size
  - 2048px on the long edge
  - JPEG format, sRGB, quality ~85%

These files are ready to upload directly to your MLS system.

Generated by AutoQC - autoqc.io
`;

/**
 * Resize a photo blob to MLS spec using canvas.
 * - Max 2048px on long edge
 * - JPEG quality that yields approx 2MB or less
 */
async function resizeForMLS(blob: Blob): Promise<Blob> {
  const MAX_DIM = 2048;
  const MAX_BYTES = 2 * 1024 * 1024; // 2MB

  const bitmap = await createImageBitmap(blob);
  let { width, height } = bitmap;

  if (width > MAX_DIM || height > MAX_DIM) {
    const ratio = Math.min(MAX_DIM / width, MAX_DIM / height);
    width = Math.round(width * ratio);
    height = Math.round(height * ratio);
  }

  const canvas = new OffscreenCanvas(width, height);
  const ctx = canvas.getContext("2d");
  if (!ctx) return blob;
  ctx.drawImage(bitmap, 0, 0, width, height);

  // Binary search for JPEG quality that fits under 2MB
  let quality = 0.85;
  let out = await canvas.convertToBlob({ type: "image/jpeg", quality });

  if (out.size > MAX_BYTES) {
    // Try lower qualities until under 2MB
    for (const q of [0.75, 0.65, 0.55, 0.45]) {
      out = await canvas.convertToBlob({ type: "image/jpeg", quality: q });
      if (out.size <= MAX_BYTES) break;
    }
  }

  return out;
}

async function fetchPhotoBlob(url: string): Promise<Blob | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return await res.blob();
  } catch {
    return null;
  }
}

/**
 * Build and download a ZIP of photos in the requested mode.
 */
export async function downloadPhotoZip(
  propertyId: string,
  propertyAddress: string,
  mode: "lightroom" | "full" | "mls",
  onProgress?: (p: ZipProgress) => void
): Promise<void> {
  const update = (p: ZipProgress) => onProgress?.(p);

  update({ phase: "fetching-xmp", done: 0, total: 1 });
  const res = await fetch(`/api/properties/${propertyId}/xmp`);
  if (!res.ok) {
    throw new Error("Failed to fetch photo manifest");
  }
  const data = await res.json();
  const sidecars: Sidecar[] = data.sidecars || [];

  if (sidecars.length === 0) {
    throw new Error("No photos to export");
  }

  const zip = new JSZip();

  if (mode === "lightroom") {
    zip.file("README.txt", README_LIGHTROOM);
  } else if (mode === "mls") {
    zip.file("README.txt", README_MLS);
  }

  update({ phase: "downloading", done: 0, total: sidecars.length });

  const queue = [...sidecars];
  let completed = 0;

  const worker = async () => {
    while (queue.length > 0) {
      const sc = queue.shift();
      if (!sc) break;

      update({
        phase: mode === "mls" ? "resizing" : "downloading",
        done: completed,
        total: sidecars.length,
        currentFileName: sc.photoFileName,
      });

      try {
        const blob = await fetchPhotoBlob(sc.photoUrl);
        if (!blob) {
          completed++;
          continue;
        }

        if (mode === "mls") {
          const resized = await resizeForMLS(blob);
          // Use .jpg extension for MLS output
          const mlsName = sc.photoFileName.replace(
            /\.(jpg|jpeg|png|webp|tiff|tif)$/i,
            "_mls.jpg"
          );
          zip.file(mlsName, resized);
        } else {
          zip.file(sc.photoFileName, blob);
          if (mode === "lightroom") {
            zip.file(sc.xmpFileName, sc.xmpContent);
          }
        }
      } catch (err) {
        console.error("Failed to process", sc.photoFileName, err);
      }
      completed++;
      update({
        phase: mode === "mls" ? "resizing" : "downloading",
        done: completed,
        total: sidecars.length,
      });
    }
  };

  await Promise.all([worker(), worker(), worker(), worker()]);

  update({ phase: "zipping", done: 0, total: 1 });
  const zipBlob = await zip.generateAsync(
    { type: "blob", compression: "STORE" },
    (metadata) => {
      update({
        phase: "zipping",
        done: Math.round(metadata.percent),
        total: 100,
      });
    }
  );

  const safeAddress = propertyAddress
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 60);
  const modeLabel =
    mode === "lightroom" ? "Lightroom" : mode === "mls" ? "MLS" : "Full";
  const zipName = `AutoQC_${modeLabel}_${safeAddress || "export"}.zip`;

  const url = URL.createObjectURL(zipBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = zipName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  update({ phase: "done", done: sidecars.length, total: sidecars.length });
}

// Backwards-compat export for any existing callers
export const downloadLightroomZip = (
  propertyId: string,
  propertyAddress: string,
  onProgress?: (p: ZipProgress) => void
) => downloadPhotoZip(propertyId, propertyAddress, "lightroom", onProgress);
