#!/bin/bash

# PhotoQC - Deploy AWS Infrastructure
# This script deploys the CloudFormation stack that creates:
# - S3 bucket for photos
# - SQS queue for QC jobs
# - RDS PostgreSQL database
# - Lambda functions (placeholder code, replaced by deploy-lambda.sh)
# - IAM roles and VPC

set -e

echo "=================================="
echo "PhotoQC Infrastructure Deployment"
echo "=================================="
echo ""

# Check AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "ERROR: AWS CLI not installed"
    echo "Install with: brew install awscli"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "ERROR: AWS credentials not configured"
    echo "Run: aws configure"
    echo "You need: Access Key ID, Secret Access Key, Region (us-east-1)"
    exit 1
fi

AWS_REGION=${AWS_REGION:-us-east-1}
STACK_NAME="photoqc-infrastructure"

# Prompt for DB password
read -sp "Enter a database password (min 8 chars, letters + numbers): " DB_PASSWORD
echo ""

if [ ${#DB_PASSWORD} -lt 8 ]; then
    echo "ERROR: Password must be at least 8 characters"
    exit 1
fi

echo ""
echo "Deploying CloudFormation stack..."
echo "Region: $AWS_REGION"
echo "This will take 10-15 minutes (mostly the RDS database)"
echo ""

aws cloudformation deploy \
    --template-file infrastructure/cloudformation.yaml \
    --stack-name $STACK_NAME \
    --parameter-overrides DBPassword=$DB_PASSWORD \
    --capabilities CAPABILITY_NAMED_IAM \
    --region $AWS_REGION

if [ $? -eq 0 ]; then
    echo ""
    echo "Infrastructure deployed successfully."
    echo ""

    # Extract outputs
    BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' --output text --region $AWS_REGION)
    QUEUE_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`QueueUrl`].OutputValue' --output text --region $AWS_REGION)
    DB_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`DatabaseEndpoint`].OutputValue' --output text --region $AWS_REGION)

    echo "Save these values to your .env file:"
    echo ""
    echo "AWS_REGION=$AWS_REGION"
    echo "AWS_S3_BUCKET=$BUCKET"
    echo "AWS_SQS_QUEUE_URL=$QUEUE_URL"
    echo "DATABASE_URL=postgresql://photoqc_admin:$DB_PASSWORD@$DB_ENDPOINT:5432/photoqc"
    echo ""
    echo "Writing to .env.local automatically..."

    # Write/update .env.local
    cat > .env.local <<EOF
# Generated by deploy-infrastructure.sh on $(date)
AWS_REGION=$AWS_REGION
AWS_S3_BUCKET=$BUCKET
AWS_SQS_QUEUE_URL=$QUEUE_URL
DATABASE_URL=postgresql://photoqc_admin:$DB_PASSWORD@$DB_ENDPOINT:5432/photoqc
EOF

    echo ""
    echo "=================================="
    echo "Next steps:"
    echo "1. Add ANTHROPIC_API_KEY to .env.local"
    echo "2. Add STRIPE keys to .env.local"
    echo "3. Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to .env.local"
    echo "4. Run: npx prisma db push"
    echo "5. Run: ./scripts/deploy-lambda.sh"
    echo "=================================="
else
    echo "Deployment failed. Check CloudFormation console for details."
    exit 1
fi
